### ISSUE TITLE
Support Sphinx-style docstrings

### ISSUE THREAD

**Issue by rubik** [moskytw/clime#16]
First of all, let me say that clime is absolutely awesome!

However, I'd like to be able to use clime with functions that use Sphinx format, like this:
http://sphinx-doc.org/domains.html#info-field-lists

Basically, what need to be supported is the `:param:` directive and maybe its type.

It would be a great addition and could simplify the work.

**Comment by moskytw** [comment]
I noted it into my own to-do list. :)
